import type { Metadata } from "next";
import icon from './common/Images/icon.svg'

export const metadata: Metadata = {
  title: "Chodźmy w góry!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={icon.src} />
      </head>
      <body>
        {children}
      </body>
    </html >
  );
}
