import type { Metadata } from "next";
import icon from './common/Images/icon.svg'
import { Kameron } from 'next/font/google';
import StyledComponentsRegistry from "./core/StyledComponents/register";
import { GlobalStyle } from "./core/StyledComponents/GlobalStyles";
import { Footer } from "./common/Footer/footer";
import { Navbar } from "./common/Navbar/navbar";

const kameron = Kameron({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-kameron',
  weight: ['400', '500', '600', '700',]
});

export const metadata: Metadata = {
  title: "Chodźmy w góry!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href={icon.src} />
      </head>
      <body className={kameron.className}>
        <StyledComponentsRegistry>
          <Navbar />
          <GlobalStyle />
          {children}
          <Footer />
        </StyledComponentsRegistry>
      </body>
    </html >
  );
}
