import type { Metadata } from "next";
import icon from "./common/Images/icon.svg";
import { Kameron } from "next/font/google";
import StyledComponentsRegistry from "./core/StyledComponents/register";
import { GlobalStyle } from "./core/StyledComponents/GlobalStyles";
import { Footer } from "./common/Footer/footer";
import { TanstackProvider } from "./core/TanstackQuery/tanstackProvider";
import { Toaster } from "react-hot-toast";

const kameron = Kameron({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-kameron",
    weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
    title: "Chodźmy w góry!",
    description: "Generated by create next app",
};

export default function RootLayout({}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="icon" href={icon.src} />
            </head>
            <body className={kameron.className}>
                <StyledComponentsRegistry>
                    <TanstackProvider>
                        {/* <Navigation /> */}
                        <GlobalStyle />
                        <Footer />
                    </TanstackProvider>
                </StyledComponentsRegistry>
                <Toaster
                    toastOptions={{
                        style: {
                            textAlign: "center",
                        },
                    }}
                />
            </body>
        </html>
    );
}
